config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  resources :users, only: [:index, :show] do
    resources :requests, only: [:create], shallow:true
  end
  resources :user_interests, only: [:create]
  resources :requests, only: [:index, :show, :update], shallow:true
  resources :conversations do
    resources :messages
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: "User"
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: "User"

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender, { scope: :recipient }

  scope :between, -> (sender, recipient) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender.id, recipient.id, recipient.id, sender.id)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @conversations = Conversation.all
  end

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id])
      .present?
      @conversation = Conversation.between(params[:sender_id],
        params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_messages_path(@conversation)
  end

  private

  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/views/conversations/_index.html.erb
<div class="ui segment">
  <h3>Mailbox</h3>
  <div class="ui list">
    <div class="item">
      <% @conversations.each do |conversation| %>
        <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
          <% if conversation.sender_id == current_user.id %>
            <% recipient = User.find(conversation.recipient_id) %>
          <% else %>
            <% recipient = User.find(conversation.sender_id) %>
          <% end %>
          <%= link_to recipient.first_name,   conversation_messages_path(conversation)%>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="ui segment">
  <h3>All Users</h3>
  <div class="ui list">
    <% @users.each do |user| %>
      <% if user.id != current_user.id %>
        <div class="item">
          <%= user.first_name %> <%= link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/conversations/index.html.erb
<div class="ui segment">
  <h3>Mailbox</h3>
  <div class="ui list">
    <div class="item">
      <% @conversations.each do |conversation| %>
        <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
          <% if conversation.sender_id == current_user.id %>
            <% recipient = User.find(conversation.recipient_id) %>
          <% else %>
            <% recipient = User.find(conversation.sender_id) %>
          <% end %>
          <%= link_to recipient.first_name,   conversation_messages_path(conversation)%>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="ui segment">
  <h3>All Users</h3>
  <div class="ui list">
    <% @users.each do |user| %>
      <% if user.id != current_user.id %>
        <div class="item">
          <%= user.first_name %> <%= link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
        </div>
      <% end %>
    <% end %>
  </div>
</div>