config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  resources :users, only: [:index, :show] do
    resources :requests, only: [:create], shallow:true
  end
  resources :user_interests, only: [:create]
  resources :requests, only: [:index, :show, :update], shallow:true
  resources :conversations do
    resources :messages
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_interests, dependent: :destroy
  has_many :interests, through: :user_interests
  has_many :sent_requests, foreign_key: "sender_id", class_name: "Request"
  has_many :received_requests, foreign_key: "receiver_id", class_name: "Request"

  validates :first_name, :last_name, :email, presence: true

  geocoded_by :current_city
  after_validation :geocode, if: :current_city_changed?

  def create_user_interests(interest_ids)
    if interest_ids
      interest_ids.each do |interest_id|
        self.user_interests.create(interest_id: interest_id)
      end
    end
  end

  def requests(status=nil)
    if status.present?
      sent_requests.where(status: status) + received_requests.where(status: status)
    else
      sent_requests + received_requests
    end
  end

  def to_s
    "#{first_name} #{last_name[0]}."
  end

  def self.filter(current_user, selected_interest_ids)
    if selected_interest_ids.empty?
      self.where
          .not(id: current_user)
          .uniq
    else
      self.where
          .not(id: current_user)
          .joins(:interests)
          .where('interests.id IN (?)', selected_interest_ids)
          .uniq
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :load_session, only: [:index]

  def index
    @users = User.filter(current_user, get_selected_interest_ids).where.not(latitude: nil, longitude: nil)
    @interests = Interest.where("id IN (?)", get_selected_interest_ids)

    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude

    end
  end

    def to_s
    name
  end

  def show
    @user = User.find(params[:id])
    @buddies = User.all.select{ |user| user != @user }.sample(3)
    @request = Request.new
    if user_signed_in?
      @receive_notication = Request.find_by(receiver_id: current_user.id, sender_id: @user.id)
      @send_request = Request.find_by(sender_id: current_user.id, receiver_id: @user.id)
    end
  end

  private

  def load_session
    session["init"] = true
  end

  def get_selected_interest_ids
    if current_user.present?
      @my_data = current_user.interest_ids
    else
      @my_data = session[:selected_interest_ids].map(&:to_i)
    end
  end
end

app/views/users/_test-card.html.erb
<div class="test-card">
  <div class="test-card-top" style="background-image: linear-gradient(-225deg, rgba(255, 226, 79,0.1) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path user.picture %>)">
  </div>
  <div class="test-card-bottom">
    <div class="align-center">
    <%= link_to "#{user.first_name}, #{user.age}", user_path(user), class: "btn-medium btn-user-listing"  %>
    <%= image_tag user.picture, class: "test-users-avatar" %>
     <div class="align-center">
    <p><%= user.current_city %></p>
    <%= image_tag "globe.png", class: "globe-avatar"%>
    </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="user-index-container">
  <div class="user-index-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'background.jpg' %>);">
    <div class="banner-content">
      <h1>Discover your travel crushs</h1>
      <p class=""><kbd>I love:</kbd> <%= "#{@interests.pluck(:name).join(', ').downcase}"%></p>
      <br>
      <p><%= link_to 'Edit interests', root_path, class: 'btn-sm btn-default' %></p>
    </div>
  </div>

  <div class="user-index-bottom">
    <div class="user-index-left">
      <div class="card-users-listing">
        <div class="row">
          <% @users.each do |user| %>
            <div class="col-xs-6 col-md-4">
              <%= render "test-card", user: user %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="user-index-right">
      <div id="map"></div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
        <script>
          $(document).ready(function() {
            var handler = Gmaps.build('Google');
            handler.buildMap({ internal: { id: 'map' }, provider: { scrollwheel: false } }, function() {
              markers = handler.addMarkers(<%= raw @hash.to_json %>);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
              if (markers.length == 0) {
                handler.getMap().setZoom(2);
              } else if (markers.length == 1) {
                handler.getMap().setZoom(14);
              }
            });
          });
        </script>
<% end %>

<% content_for(:footer_class, "hidden") %>

app/views/users/show.html.erb
  <div class="user-index-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'background.jpg' %>);">
    <div class="banner-content">
        <div class="banner-content-text">
          <div class="span-center">
            <a href="https://www.facebook.com/apollinesntck"><i class="fa fa-facebook-square fa-2x" aria-hidden="true" style="color:white; margin-right:8px;"></i></a>
            <a href="#"><i class="fa fa-instagram fa-2x" aria-hidden="true" style="color:white";></i></a>
          </div>
            <h2><%= @user.first_name %> <%= @user.last_name %>, <%= @user.age %></h2>
            <p><%= @user.current_city %></p>
      </div>
      <div><%= image_tag @user.picture, class: "avatar" %></div>
    </div>
  </div>

  <div class="user-card">
    <br>

    <div class="kbd-flex">
      <p><kbd><%= "#{@user.interests.join(', ').downcase}"%><kbd></p>
      <br>
    </div>


    <h1> Description </h1>
    <i><%= @user.description %></i>
    <br>
    <p class="card-text"><small class="text-muted">Updated in January 2017</small></p>

    <div class="button-request">
      <% if user_signed_in?  && @receive_notication %>
        <div class="text-center">
          <p>This crush is waiting for your answer</p>
          <%= link_to "Go to dashboard", requests_path, class:'btn btn-default' %>
        </div>
      <% elsif user_signed_in? && @send_request %>
        <div class="text-center">
          <p>Already notified</p>
          <%= link_to "Go to dashboard", requests_path, class:'btn btn-default' %>
        </div>
      <% else %>
        <%= render 'requests/new', user: @user, request: @request %>
      <% end %>
      <br>
    </div>

    <h1> Travel stories </h1>

    <div class="travel-stories">
      <div class="travel-stories-left" style="background-image: url(<%= image_path 'apo_travel.jpg' %>);">
      </div>
      <div class="travel-stories-right">
        <h2><strong>Argentina</strong></h2>
        <p>Aug 1, 2016 — Oct 1, 2016</p>
        <br>
         <div class="buddies">
          <% @buddies.each do |user| %>
            <%= link_to user_path(user) do %>
              <div class="card-buddy text-center">
                <div><%= image_tag user.picture, class: "buddy-photo" %></div>
                <p><%= user.first_name %> travelled with me!</p>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
<br>
    <div class="travel-stories">
     <div class="travel-stories-left" style="background-image: url(<%= image_path 'australia.jpg' %>);">
      </div>
      <div class="travel-stories-right">
        <h2><strong> Australia</strong></h2>
        <p>Jan 18, 2014 — Sept 3, 2014</p>
        <br>
        <div class="buddies">
          <% @buddies.each do |user| %>
            <%= link_to user_path(user) do %>
              <div class="card-buddy text-center">
                <div><%= image_tag user.picture, class: "buddy-photo" %></div>
                <p><%= user.first_name %> travelled with me!</p>
              </div>
            <% end %>
          <% end %>
        </div>
        <div>

        </div>
      </div>
    </div>
    <br>
      <%= link_to "Go back", users_path, class:'btn btn-default' %>
  </div>