config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  resources :users, only: [:index, :show] do
    resources :requests, only: [:create], shallow:true
  end
  resources :user_interests, only: [:create]
  resources :requests, only: [:index, :show, :update], shallow:true
  resources :conversations do
    resources :messages
  end
end

app/models/user_interest.rb
class UserInterest < ApplicationRecord
  belongs_to :user
  belongs_to :interest

  validates :user, uniqueness: {scope: :interest}
  validates :user_id, presence: true
  validates :interest_id, presence: true
end

app/controllers/user_interests_controller.rb
class UserInterestsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:create]

  def create
    if user_signed_in?
      current_user.create_user_interests(interest_ids)
    else
      session[:selected_interest_ids] = interest_ids
    end
    redirect_to users_path
  end

  def to_s
    name
  end

private

  def interest_ids
    params[:user_interest][:interest_id].reject(&:blank?)
  end
end

app/views/user_interests/_new.html.erb
<%= simple_form_for :user_interest,  url: user_interests_path(), method: :post do |f| %>

  <div class="interests-wrapper">
    <%= f.collection_check_boxes :interest_id, Interest.all[0..3], :id, :name do |interest| %>
      <label class="card-interest-wrapper">
        <%= interest.check_box %>
        <%#= cl_image_url interest.object.picture.path %>
        <div class="card-interest" style=" background-image: url(<%= set_image_for_checkbox(interest.text)%>)">
          <h2 class="card-interest-name">
            <%= interest.text %>
          </h2>
          <i class="fa fa-heart-o heart-icon fa-3x" aria-hidden="true"></i>
        </div>
      </label>
    <% end %>

    <div id="submit-interests">
      <h1> TRAVEL CRUSH </h1>
      <p> CONNECT NOMADS </p>
      <h2> Select what you love and be sure to travel with someone like you</h2>
      <%= f.button :submit, 'Explore', class: "btn_home btn-lg btn-info"%>
    </div>
    <%= f.collection_check_boxes :interest_id, Interest.all[4..7], :id, :name do |interest| %>
      <label class="card-interest-wrapper">

        <%= interest.check_box %>

        <%#= cl_image_url interest.object.picture.path %>
        <div class="card-interest" style="background-image: url(<%= set_image_for_checkbox(interest.text)%>)">
          <h2 class="card-interest-name">
            <%= interest.text %>
          </h2>
          <i class="fa fa-heart-o heart-icon fa-3x" aria-hidden="true"></i>
        </div>
      </label>
    <% end %>
    <%= f.collection_check_boxes :interest_id, Interest.all[8..10], :id, :name do |interest| %>
      <label class="card-interest-wrapper">

        <%= interest.check_box %>

        <%#= cl_image_url interest.object.picture.path %>
        <div class="card-interest" style="background-image: url(<%= set_image_for_checkbox(interest.text)%>)">
          <h2 class="card-interest-name">
            <%= interest.text %>
          </h2>
          <i class="fa fa-heart-o heart-icon fa-3x" aria-hidden="true"></i>
        </div>
      </label>
    <% end %>
  </div>
<% end %>